version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: your-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: AFTAS
      MYSQL_USER: root
      MYSQL_PASSWORD: 
  springboot-app:
    build:
      context: ./Aftas
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/AFTAS?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_LIQUIBASE_ENABLED : true

  angular-app:
    build:
      context: ./Aftas-v2
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - springboot-app