version: '3'

services:
  mysql:
    image: mysql
    restart: always
    container_name: MySQL_container
    environment:
      MYSQL_ROOT_PASSWORD: a
    volumes:
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    
  springboot-app:
    build:
      context: ./Aftas
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/AFTAS?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: a
      SPRING_LIQUIBASE_ENABLED : true

  angular-app:
    build:
      context: ./Aftas-v2
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - springboot-app